// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://breldmutslldticetknm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyZWxkbXV0c2xsZHRpY2V0a25tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjQxNTcsImV4cCI6MjA2NzEwMDE1N30.qglM8mE0tg1eMOnf7cgAKBOrM_4RUYlpFfMcBlNQT6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});